version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "batch-signer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-m1i4ef62igzb"
s3_prefix = "batch-signer"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
