AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  batch-signer

  Sample SAM Template for batch-signer

Resources:
  OrchestratorStateMachine:
    Type: AWS::Serverless::StateMachine     
    Properties:
      DefinitionUri: statemachine/orchestrator.asl.json
      DefinitionSubstitutions:
        GetAllKeysFunctionArn: !GetAtt GetAllKeysFunction.Arn
      Policies:         
        - LambdaInvokePolicy:
            FunctionName: !Ref GetAllKeysFunction 
        - LambdaInvokePolicy:
            FunctionName: !Ref BatchSignerFunction 
        - LambdaInvokePolicy:
            FunctionName: !Ref GetNextBatchFunction 
        - SQSSendMessagePolicy:
            QueueName: !Ref GetNextBatchQueue
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable 
        - DynamoDBCrudPolicy:
            TableName: !Ref KeysTable

  GetAllKeysFunction:
    Type: AWS::Serverless::Function    
    Properties:
      CodeUri: functions/get-all-keys/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref KeysTable
      Environment:
        Variables:
          KEYS_TABLE: !Ref KeysTable
      Timeout: 60

  BatchSignerFunction:
    Type: AWS::Serverless::Function     
    Properties:
      CodeUri: functions/batch-signer/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable 
        - DynamoDBCrudPolicy:
            TableName: !Ref KeysTable

  KeyGenFunction:
    Type: AWS::Serverless::Function    
    Properties:
      CodeUri: functions/key-gen/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref KeysTable
      Environment:
        Variables:
          KEYS_TABLE: !Ref KeysTable
      Timeout: 60

  SeedDataFunction:
    Type: AWS::Serverless::Function    
    Properties:
      CodeUri: functions/seed-data/
      Handler: app.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable
      Environment:
        Variables:
          MESSAGES_TABLE: !Ref MessagesTable
      Timeout: 900
      MemorySize: 1280

  GetNextBatchFunction:
    Type: AWS::Serverless::Function    
    Properties:
      CodeUri: functions/get-next-batch/
      Handler: app.handler
      Runtime: nodejs14.x
      ReservedConcurrentExecutions: 1 # important!
      Architectures:
        - x86_64
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt GetNextBatchQueue.Arn
            BatchSize: 1
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable 
        - DynamoDBCrudPolicy:
            TableName: !Ref ProgressTable
      Environment:
        Variables:
          MESSAGES_TABLE: !Ref MessagesTable
          PROGRESS_TABLE: !Ref ProgressTable

  GetNextBatchQueue:
    Type: AWS::SQS::Queue

  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: CollectionId 
          AttributeType: S
        - AttributeName: Message 
          AttributeType: S
      KeySchema:
        - AttributeName: CollectionId 
          KeyType: HASH
        - AttributeName: Message 
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 16
        WriteCapacityUnits: 16

  KeysTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: PubKey
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  ProgressTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
