AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  batch-signer

  Sample SAM Template for batch-signer

Resources:
  OrchestratorStateMachine:
    Type: AWS::Serverless::StateMachine     
    Properties:
      DefinitionUri: statemachine/orchestrator.asl.json
      DefinitionSubstitutions:
        SplitterFunctionArn: !GetAtt SplitterFunction.Arn
        BatchSignerFunctionArn: !GetAtt BatchSignerFunction.Arn
        KeysTableName: !Ref KeysTable
      Policies:         
        - LambdaInvokePolicy:
            FunctionName: !Ref BatchSignerFunction 
        - LambdaInvokePolicy:
            FunctionName: !Ref SplitterFunction 
        - SQSSendMessagePolicy:
            QueueName: !GetAtt BatchQueue.QueueName
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable 
        - DynamoDBCrudPolicy:
            TableName: !Ref KeysTable

  BatchSignerFunction:
    Type: AWS::Serverless::Function     
    Properties:
      CodeUri: functions/batch-signer/
      Handler: app.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable 
        - DynamoDBCrudPolicy:
            TableName: !Ref KeysTable
        - DynamoDBCrudPolicy:
            TableName: !Ref LocksTable
        - SQSPollerPolicy:
            QueueName: !GetAtt BatchQueue.QueueName
      Environment:
        Variables:
          MESSAGES_TABLE: !Ref MessagesTable
          KEYS_TABLE: !Ref KeysTable
          LOCKS_TABLE: !Ref LocksTable
          BATCH_QUEUE: !Ref BatchQueue
      Timeout: 300

  KeyGenFunction:
    Type: AWS::Serverless::Function    
    Properties:
      CodeUri: functions/key-gen/
      Handler: app.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref KeysTable
      Environment:
        Variables:
          KEYS_TABLE: !Ref KeysTable
      Timeout: 60

  SeedDataFunction:
    Type: AWS::Serverless::Function    
    Properties:
      CodeUri: functions/seed-data/
      Handler: app.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable
      Environment:
        Variables:
          MESSAGES_TABLE: !Ref MessagesTable
      Timeout: 900
      MemorySize: 512

  SplitterFunction:
    Type: AWS::Serverless::Function    
    Properties:
      CodeUri: functions/splitter/
      Handler: app.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable 
        - SQSSendMessagePolicy:
            QueueName: !GetAtt BatchQueue.QueueName
      Environment:
        Variables:
          MESSAGES_TABLE: !Ref MessagesTable
          BATCH_QUEUE: !Ref BatchQueue
      Timeout: 600
      MemorySize: 512

  VerifierFunction:
    Type: AWS::Serverless::Function    
    Properties:
      CodeUri: functions/verifier/
      Handler: app.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable 
      Environment:
        Variables:
          MESSAGES_TABLE: !Ref MessagesTable
      Timeout: 600
      MemorySize: 512

  BatchQueue:
    Type: AWS::SQS::Queue

  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: CollectionId 
          AttributeType: S
        - AttributeName: MessageId
          AttributeType: S
      KeySchema:
        - AttributeName: CollectionId 
          KeyType: HASH
        - AttributeName: MessageId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  KeysTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: PubKey
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  LocksTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: LockId
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
